### ISSUE TITLE
No package matching 'mongodb-org-server' is available

### ISSUE THREAD

**Issue by mehrenreich** [girder/ansible-role-girder-mongodb#30] opened 2021-02-28 11:07 UTC
When trying to install on Ubuntu-20.04, following error is thrown:

```
TASK [girder.mongodb : Install MongoDB packages] ***************************************************************************************************************************
fatal: [mongo-1]: FAILED! => {"changed": false, "msg": "No package matching 'mongodb-org-server' is available"}
```

Playbook:
```
---
- hosts: mongo
  roles:
    - { role: girder.mongodb, tags: [mongodb] }
```

Requirements file:
```
---
- girder.mongodb
```

**Comment by brianhelba** [comment] 2021-02-28 21:40
@mehrenreich Thanks for the report. It looks like the issue is that MongoDB 4.2 (the version currently installed by this role default) [doesn't support Ubuntu 20.04](https://docs.mongodb.com/v4.2/tutorial/install-mongodb-on-ubuntu/) .

**Comment by brianhelba** [comment] 2021-02-28 21:42
This should fix the issue: https://github.com/girder/ansible-role-girder-mongodb/pull/31

**Comment by brianhelba** [comment] 2021-02-28 21:52
Should be fixed now.

**Closed by brianhelba** 2021-02-28 21:52 UTC
